title: Studioers
email: coinkriptobilgi@gmail.com
description: >- 
  Digital Revenue Blueprint & No-Code Engineering.
url: "https://studioers.xyz"
baseurl: ""

# Temayı "cayman" olarak değil, doğrudan GitHub destekli hale getirelim
theme: jekyll-theme-cayman

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - admin/
