title: Studioers
email: coinkriptobilgi@gmail.com
description: >- 
  Digital Revenue Blueprint & No-Code Engineering.
url: "https://studioers.xyz"
baseurl: ""

# En stabil ve hatasız tema
theme: minima

encoding: "utf-8"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - admin/
  - node_modules/
  - vendor/
  # Sytle SCSS'i okuması için ekle
sass:
  style: compressed
