backend:
  name: github
  repo: brobrovb/studioers
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Yazilar"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Baslik", name: "title", widget: "string" }
      - { label: "Icerik", name: "body", widget: "markdown" }
