title: Studioers
email: coinkriptobilgi@gmail.com
description: >- 
  Digital Revenue Blueprint & No-Code Engineering.
baseurl: "" 
url: "https://studioers.xyz"

# Tema seçimi (GitHub Pages'in desteklediği en şık ve basit tema)
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
