backend:
  name: github
  repo: brobrovb/studioers # Buraya kendi kullanıcı adını yaz (Örn: brobrovb/studioers)
  branch: main # Eğer ana branch adın farklıysa (master gibi) onu yaz

media_folder: "images" # Yüklediğin resimler bu klasöre gider
public_folder: "/images"

collections:
  - name: "blog"
    label: "Makaleler"
    folder: "articles" # Makalelerin yükleneceği klasör (HTML sayfaların burada olduğu için)
    create: true
    slug: "{{slug}}"
    extension: "html" # Dosyaları .html olarak kaydetmesi için
    format: "frontmatter" # AdSense botu için gereken meta verileri başa ekler
    fields:
      - { label: "Başlık", name: "title", widget: "string" }
      - { label: "Yayın Tarihi", name: "date", widget: "datetime" }
      - { label: "Kategori", name: "category", widget: "string" }
      - { label: "Kapak Resmi", name: "image", widget: "image", required: false }
      - { label: "İçerik", name: "body", widget: "markdown" }
